### ISSUE TITLE
Problem: installation is difficult when Composer is unavailable

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-atom#80]
This role uses the `community.general.composer` Ansible module to provision certain AtoM dependencies at deploy time that are managed with Composer, the PHP package manager. However, this role is not managing the installation of Composer, forcing the user to install it beforehand. Furthermore, Composer depends on PHP, which this role aims to manage·

Users have been addressing this issue outside ansible-atom, managing the complexity from their own playbooks. These are two ways I've seen this issue being addressed:
1. Depend on artefactual-labs/ansible-role-composer to install Composer and its dependencies, or
2. Manually installing Composer and its dependencies.

I'm not sure what's the right pattern in this space. In https://github.com/artefactual-labs/ansible-archivematica-src, we manage the installation of Pip which is the standard Python package manager. If this role learned to install Composer (through a simplified version of artefactual-labs/ansible-role-composer), then users would see the process simplified.

**Comment by djjuhasz** [comment]
@sevein I'm not a fan of rolling our own ansible composer role.  I don't think we have the time or resources to effectively manage ansible roles for common apps like nginx, PHP, and composer.  Maybe instead of adding composer to the atom role we should remove PHP installation from the AtoM role, and manage the install order in our playbooks?

**Comment by sevein** [comment]
I can see that! It makes me feel though that roles are leaky abstractions - I like to see them as self-contained deployable untils but they're certainly not. Playbooks only used to need to manage service dependencies like Gearman, but now we're also dealing with our software build and runtime dependencies (Composer, PHP). How far is ok to push this pattern of composition? E.g. would Ansible users also deal with the installation of Apache FOP + JDK? That seems pretty impractical, but I guess I'm just trying to know where is the right place to draw the line :laughing:

**Comment by djjuhasz** [comment]
Yes, I wish that Ansible roles were more independent and Ansible allowed more flexibility about when roles are run in the playbook, what data is passed between a playbook and roles, and allowed composition of roles within roles. I also wish Playbooks were not tightly coupled to hosting inventory, or there was a level of abstraction between playbooks and roles that didn't depend on inventory. :(

In my opinion one of our main principles for designing our Ansible playbooks should be to use well-maintained, public roles whenever possible.  I believe good, well-maintained Galaxy roles exist for Composer and PHP, but I would be surprised if the same is true for Apache FOP.  I'm not sure, but I would guess that using a public role to deploy JDK would be more maintainable and robust in the long run, but the work to separate JDK deployment out of the current AtoM role may not be worth it at this point.

**Comment by sevein** [comment]
And if you made a change, how do you propagate the requirement to your consumers? E.g. would we need to update all our existing playbooks? That sounds like a lot of work too, circling back to your point on limited time/resources.

**Comment by djjuhasz** [comment]
I would argue that the cost maintaining our own roles and troubleshooting deployment problems from bugs in our custom roles are going to cost us more work than updating our playbooks when a new requirement is introduced.  I think you can argue that monolithic apps are easier to deploy because you don't have to deal with integration, but it ends up costing on the maintenance side, because everything is tightly coupled.  Maybe the limitations of Ansible composability make the monolithic approach better than decomposition, but I'm not convinced.

**Comment by sevein** [comment]
Very well put, David! If we decide to stop managing PHP deps from here I'm happy to update the role accordingly.

**Comment by sevein** [comment]
In #84, we started managing the installation of Composer from this role. In the long-term, we plan to rely on third-party roles to install PHP, Composer, etc...
